export const API = {
    AUTH: {
        TOKEN_REFRESH: "auth/token-refresh",
        REGISTER: {
            EMAIL: "auth/register/email",
            EMAIL_VERIFY: "auth/register/email-verify",
            EMAIL_GET_NEW_CODE: "auth/register/email-get-new-code",
            GOOGLE_AUTH: "auth/register/google-auth",
            FACEBOOK_AUTH: "auth/register/facebook-auth",
            LINKEDIN_AUTH: "auth/register/linkedin-auth",
        },
        LOGIN: {
            EMAIL: "auth/login/email",
            FORGOT_PASSWORD: {
                REQUEST: "auth/login/forgot-password/request",
                RESET: "auth/login/forgot-password/reset",
                VERIFY: "auth/login/forgot-password/verify",
            },
        },
        LOGOUT: "auth/logout",
        AI: {
            INDEX: "auth/ai",
            GET_USER_DATA: "auth/ai/get-user-datas",
        },
    },
    PROFILE: {
        INDEX: "profile",
        INFO: {
            ME: "profile/info/me",
            DISPLAY_PERMISSION: "profile/info-display-permissions",
        },
        BLOG: {
            INDEX: "profile/blog/posts",
            ARCHIVE: "profile/blog/posts/archives",
            ARCHIVE_SLUG: "profile/blog/posts/{slug}/archive",
            SLUG: "profile/blog/posts/{slug}",
            OTHER_USER_ID: "profile/blog/posts-for-others/{user_id}",
        },
        OTHER: {
            INDEX: "profile/other",
            USER_INFO: "profile/other-users/info/{user_id}",
        },
        TWO_FA: {
            ENABLE: "profile/2fa/enable",
            DISABLE: "profile/2fa/disable",
            VERIFY_EMAIL_FOR_TWO_FACTOR:
                "profile/2fa/verifiy-email-for-two-factor",
        },
        NETWORK: {
            INDEX: "profile/network",
            BLOCKS: "profile/network/blocks",
            BLOCKS_ID: "profile/network/blocks/{id}",
            BLOCKS_ID_RESTORE: "profile/network/blocks/{user_id}/restore",
            CONNECTIONS: "profile/network/connections",
            CONNECTIONS_ID: "profile/network/connections/{id}",
            CONNECTIONS_ID_BLOCK: "profile/network/connections/{user_id}/block",
            INVITATIONS: "profile/network/invitations",
            INVITATIONS_ID_ACCEPT: "profile/network/invitations/{id}/accept",
            INVITATIONS_ID_IGNORE: "profile/network/invitations/{id}/ignore",
        },
        MARKETPLACE: {
            ITEMS: "profile/marketplace/items",
            OTHER_USER_ID: "profile/marketplace/items-for-others/{user_id}",
            ARCHIVE: "profile/marketplace/items/archives",
            ARCHIVE_SLUG: "profile/marketplace/items/{slug}/archive",
            SLUG: "profile/marketplace/items/{slug}",
        },
        INVESTMENT: {
            ITEMS: "profile/investment/investment-items",
            OTHER_USER_ID: "profile/investment/items-for-others/{user_id}",
            ARCHIVE_SLUG: "profile/investment/investment-items/{slug}/archive",
            SLUG: "profile/investment/investment-items/{slug}",
        },
        OUTREACH_HUB: {
            ITEMS: "profile/outreach-hub/items",
            OTHER_USER_ID: "profile/outreach-hub/items-for-others/{user_id}",
            ITEMS_ARCHIVE: "profile/outreach-hub/items/archives",
            ARCHIVE_SLUG: "profile/outreach-hub/items/{slug}/archive",
            SLUG: "profile/outreach-hub/items/{slug}",
            LAST_UPDATE_REPORT: "profile/outreach-hub/last-update-report",
        },
        BOOKMARK: {
            BLOG: "profile/bookmark/blog",
            MARKETPLACE: "profile/bookmark/marketplace",
            INVESTMENT: "profile/bookmark/investment",
            OUTREACH_HUB: "profile/bookmark/outreach-hub",
        },
        UPDATE_FIREBASE_TOKEN: "profile/update-firebase-token",
        DELETE_ACCOUNT: "profile/delete-account",
        BUSINESS: "profile/business",
        DEVICES: "profile/devices",
        UPDATE_PASSWORD: "profile/update-password",
    },
    GLOBAL: {
        COUNTRY_LIST_FOR_FILTER: "global/country-list-for-filter",
        SEARCH: "global/search",
        AI: "global/home-page-ai",
    },
    MARKETPLACE: {
        INDEX: "marketplace",
        HOME_PAGE_PRODUCT_CATEGORIES:
            "marketplace/home-page-product-categories",
        HOME_PAGE_SERVICE_CATEGORIES:
            "marketplace/home-page-service-categories",
        LIST: "marketplace/list",
        LIST_SLUG: "marketplace/list/{slug}",
        BOOKMARK_SLUG: "marketplace/bookmark/{slug}",
        SIMILAR_SLUG: "marketplace/similar/{slug}",
        AI_CREATE_POST: "marketplace/ai/create-marketplace-item-with-ai",
        AI_FILTER: "marketplace/ai/filter-marketplace-item-with-ai",
    },
    INVESTMENT: {
        INDEX: "investment",
        INVESTMENT_ITEMS: {
            INDEX: "investment/investment-items",
            SLUG: "investment/investment-items/{slug}",
            SLUG_BOOKMARK: "investment/investment-items/{slug}/bookmark",
            SLUG_DOCUMENTS: "investment/investment-items/{slug}/documents",
            SLUG_IMAGES: "investment/investment-items/{slug}/images",
            SLUG_SIMILAR: "investment/investment-items/{slug}/similar",
            SLUG_VIDEOS: "investment/investment-items/{slug}/videos",
        },
        AI_CREATE_POST: "investment/ai/create-investment-item-with-ai",
        AI_FILTER: "investment/ai/filter-investment-item-with-ai",
    },
    OUT_REACH_HUB: {
        INDEX: "outreach-hub",
        LIST: "outreach-hub/list",
        LIST_SLUG: "outreach-hub/list/{slug}",
        SIMILAR_SLUG: "outreach-hub/similar/{slug}",
        BOOKMARK_SLUG: "outreach-hub/bookmark/{slug}",
        REPORT_FUNDRAISER_SLUG: "outreach-hub/report-fundraiser/{slug}",
        AI_CREATE_POST: "outreach-hub/ai/create-outreach-hub-item-with-ai",
        AI_FILTER: "outreach-hub/ai/filter-outreach-hub-item-with-ai",
    },
    MESSENGER: {
        CHATS: {
            INDEX: "messenger/chats",
            CHAT_CREATE_MARKETPLACE: "messenger/chats/chat-create-marketplace",
            CHAT_CREATE_INVESTMENT: "messenger/chats/chat-create-investment",
            CHAT_CREATE_OUTREACH_HUB:
                "messenger/chats/chat-create-outreach-hub",
        },
    },
    CHAT: {
        MESSENGER_CHATS: "messenger/chats",
        MESSENGER_FOLDERS: "messenger/folders",
        MESSENGER_CONTACTS: "messenger/contacts",
        MESSENGER_MESSAGES: "messenger/messages",
        MESSENGER_SLUG_CHATS: "messenger/chats/{slug}",
        MESSENGER_SLUG_PARTNER: "messenger/chats/{slug}/partner",
        MESSENGER_SLUG_FOLDER: "messenger/folders/{slug}",
        MESSENGER_FOLDER_ICONS: "messenger/folder-icons",
        MESSENGER_SLUG_FOLDER_ICONS: "messenger/folder-icons/${slug}",
        MESSENGER_FOLDERS_REORDER: "messenger/folders/reorder",
        MESSENGER_CHATS_SLUG_ACCEPT: "messenger/chats/{slug}/accept",
        MESSENGER_CHATS_SLUG_BLOCK: "messenger/chats/{slug}/block",
        MESSENGER_CHATS_SLUG_CLEAR: "messenger/chats/{slug}/clear",
        MESSENGER_MESSAGES_SLUG_READ: "messenger/messages/{slug}/read",
    },
    EXTRA: {
        PARTNERS: "extra/partners",
        MAIN_SITE_INFO: "extra/main-site-info",
        ADDITIONAL_PAGES: "extra/additional-pages",
        ADDITIONAL_PAGE_SLUG: "extra/additional-pages/{slug}",
        MEDIA: "extra/media",
        COMPANIES: "extra/companies",
        AI_CHAT_START_MESSAGE: "extra/ai-chat-start-message",
    },
    BLOG: {
        INDEX: "blog",
        LIST: "blog/list",
        NEWS: "blog/news",
        BOOKMARK_SLUG: "blog/bookmark/{slug}",
        LIKE_SLUG: "blog/like/{slug}",
        DISLIKE_SLUG: "blog/dislike/{slug}",
        LIST_SLUG: "blog/list/{slug}",
        CATEGORIES: "blog/categories",
        VIEW_SLUG: "blog/view/{slug}",
    },
    NOTIFICATIONS: {
        EXTRA_NOTIFICATIONS: "extra/notifications",
        EXTRA_NOTIFICATIONS_READ_ALL: "extra/notifications/read-all",
        EXTRA_NOTIFACATIONS_SLUG: "extra/notifications/{slug}",
        EXTRA_NOTIFICATIONS_SLUG_READ: "extra/notifications/{slug}/read",
    },
} as const
