export const MODAL_KEYS = {
    MEDIA_VIEWER_MODAL: "media-viewer-modal",
    LOGIN_MODAL: "login-modal",
    NOTIFICATION_MODAL: "notification-modal",
    AI_MODAL: "ai-modal",
    MARKETPLACE_CANCEL_MODAL: "marketplace-cancel-modal",
    INVESTMENT_CANCEL_MODAL: "investment-cancel-modal",
    OUTREACH_HUB_CANCEL_MODAL: "outreach-hub-cancel-modal",
    VISIBILITY_SETTINGS: "visibility-settings",
    VERIFY_EMAIL_ADDRESS: "verify-email-address",
    REPORT_MODAL: "report-modal",
    SUCCESS_NOTIFY_MODAL: "success-notify-modal",
    CHAT_EDIT_FOLDERS: "chat-folder-edit-modal",
    CHAT_ADD_EDIT_FOLDER: "chat-create-new-folder-modal",
    CHAT_EDIT_NEW_FOLDER_MODAL: "chat-edit-new-folder-modal",
    DELETE_CHAT: "delete-chat",
    CLEAR_CHAT: "clear-chat",
    CHAT_EXTRA_MEDIA_MODAL: "chat-extra-media-modal",
} as const
